# SIMULATION PARAMETERS
simulation_time = 40000.0
time_step = 1.0
population_cap = 10000
initial_population = 10000
initial_female_proportion = 0.5

initial_age_distribution = [20.0, 10.0]
initial_b_distribution = [0.07, 0.001]
initial_lmax_distribution = [0.1, 0.0]

mutable_b = true
mutable_lmax = false
b_mutation_rate = 0.02
lmax_mutation_rate = 0.02
b_mutation_strength = 0.006
lmax_mutation_strength = 0.012

# GLA PARAMETERS
minimum_mortality = 1e-5
aging_parameters = [1.15106610e-02, 2.71975789e-02, 4.26805906e-02]
learning_parameters = [2.93238557e-02, 3.94526937e+01, 9.41817943e-02]
growth_parameters = [1.00399978e-01, 9.23916941e-02]

# FERTILITY PARAMETERS
female_fertility_function = "brass_polynomial" # "constant", increasing", "decreasing", "brass_polynomial"
female_fertility_parameters = [2.445e-5, 14.8, 32.836]

male_fertility_function = "brass_polynomial" # "constant", increasing", "decreasing", "brass_polynomial"
male_fertility_parameters = [2.445e-5, 14.8, 32.836]
